export default 
[
    { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101", "available": "May 6", "fullavailable": "May 6, 2024, 12:00 AM", "formatavailable": "2024-05-06T00:00", "due": "May 13", "fulldue": "May 13, 2024, 11:59 PM", "formatdue": "2024-05-13T23:59", "points": "100", "fulluntil": "May 20, 2024, 11:59 PM", "formatuntil": "2024-05-20T23:59",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." },
    { "_id": "A102", "title": "Combustion Analysis", "course": "RS101", "available": "May 13", "fullavailable": "May 13, 2024, 12:00 AM", "formatavailable": "2024-05-13T00:00", "due": "May 20", "fulldue": "May 20, 2024, 11:59 PM", "formatdue": "2024-05-20T23:59", "points": "100", "fulluntil": "May 27, 2024, 11:59 PM", "formatuntil": "2024-05-27T23:59",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."   },
    { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101", "available": "May 20", "fullavailable": "May 20, 2024, 12:00 AM", "formatavailable": "2024-05-20T00:00", "due": "May 27", "fulldue": "May 27, 2024, 11:59 PM", "formatdue": "2024-05-27T23:59", "points": "100", "fulluntil": "June 3, 2024, 11:59 PM", "formatuntil": "2024-06-03T23:59",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."   },
    { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102", "available": "May 6", "fullavailable": "May 6, 2024, 12:00 AM", "formatavailable": "2024-05-06T00:00", "due": "May 13", "fulldue": "May 13, 2024, 11:59 PM", "formatdue": "2024-05-13T23:59", "points": "100", "fulluntil": "May 20, 2024, 11:59 PM", "formatuntil": "2024-05-20T23:59",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."   },
    { "_id": "A202", "title": "Flow Analysis", "course": "RS102", "available": "May 13", "fullavailable": "May 13, 2024, 12:00 AM", "formatavailable": "2024-05-13T00:00", "due": "May 20", "fulldue": "May 20, 2024, 11:59 PM", "formatdue": "2024-05-20T23:59", "points": "100", "fulluntil": "May 27, 2024, 11:59 PM", "formatuntil": "2024-05-27T23:59",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."    },
    { "_id": "A203", "title": "Heating Analysis", "course": "RS102", "available": "May 20", "fullavailable": "May 20, 2024, 12:00 AM",  "formatavailable": "2024-05-20T00:00", "due": "May 27", "fulldue": "May 27, 2024, 11:59 PM", "formatdue": "2024-05-27T23:59", "points": "100", "fulluntil": "June 3, 2024, 11:59 PM", "formatuntil": "2024-06-03T23:59",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."    },
    { "_id": "A301", "title": "Structural Design Task", "course": "RS103", "available": "May 6", "fullavailable": "May 6, 2024, 12:00 AM", "formatavailable": "2024-05-06T00:00", "due": "May 13", "fulldue": "May 13, 2024, 11:59 PM", "formatdue": "2024-05-13T23:59", "points": "100", "fulluntil": "May 20, 2024, 11:59 PM", "formatuntil": "2024-05-20T23:59",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."   },
    { "_id": "A302", "title": "Orbital Calculations", "course": "RS103", "available": "May 13", "fullavailable": "May 13, 2024, 12:00 AM", "formatavailable": "2024-05-13T00:00", "due": "May 20", "fulldue": "May 20, 2024, 11:59 PM", "formatdue": "2024-05-20T23:59", "points": "100", "fulluntil": "May 27, 2024, 11:59 PM", "formatuntil": "2024-05-27T23:59",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."    },
    { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103", "available": "May 20", "fullavailable": "May 20, 2024, 12:00 AM",  "formatavailable": "2024-05-20T00:00", "due": "May 27", "fulldue": "May 27, 2024, 11:59 PM", "formatdue": "2024-05-27T23:59", "points": "100", "fulluntil": "June 3, 2024, 11:59 PM", "formatuntil": "2024-06-03T23:59",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."    } 

];